apiVersion: v1
kind: Pod
metadata:
  name: mundial-web
  namespace: mundial
  labels:
    app: mundial-web
spec:
  containers:
    - name: mundial-web
      image: mundial-web:marvin-mollo
      imagePullPolicy: Never
      ports:
        - containerPort: 80
